### ISSUE TITLE
Latest Release Generates Payment Error Message

### ISSUE THREAD

**Issue by 1of13** [StanGirard/quivr#191]
After updating to the latest release, and having used quivr in the past without problems, I am now getting this error:

backend  | JWTError: Signature verification failed.
backend  | INFO:     172.18.0.1:48710 - "POST /upload HTTP/1.1" 402 Payment Required

What gives?

**Comment by DeacNutt** [comment]
I am having the same issue.

**Comment by willmoura** [comment]
I also have this issue

web      | - wait compiling /chat/page (client and server)...
backend  | INFO:     172.18.0.1:57550 - "OPTIONS /upload HTTP/1.1" 200 OK
backend  | INFO:     172.18.0.1:57550 - "POST /upload HTTP/1.1" 402 Payment Required
web      | - event compiled client and server successfully in 28.9s (2475 modules)

**Comment by StanGirard** [comment]
Please put your card info on openai platform.openai.com

**Comment by darkanubis0100** [comment]
I found that if your OpenAI account is up to date and you are still getting this error, clearing the cookies from 127.0.0.1 or localhost in the browser will help you resolve it. In my case I got the error because I was not logged in but no matter how many times I rebuilt the container, I never got the login.

I hope this is helpful

**Comment by darkanubis0100** [comment]
@StanGirard Can you put that in the FAQs?

**Comment by github-of-wone** [comment]
@StanGirard 
card info on openai platform.openai.com is even required if we using free account (month)
