### ISSUE TITLE
[Issue] ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE

### ISSUE THREAD

**Issue by andersir** [StanGirard/quivr#565]
I get the following error during the docker build:
```
#0 67.56 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
#0 67.56     nvidia-cudnn-cu11==8.5.0.96 from https://files.pythonhosted.org/packages/dc/30/66d4347d6e864334da5bb1c7571305e501dcb11b9155971421bb7bb5315f/nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (from torch>=1.6.0->sentence_transformers>=2.0.0->-r /code/requirements.txt (line 24)):
#0 67.56         Expected sha256 402f40adfc6f418f9dae9ab402e773cfed9beae52333f6d86ae3107a1b9527e7
#0 67.56              Got        e1c22222a1ccb6d1521656069520b6ea574b082a20c2ecbc6a484ba6ddeb3de8
#0 67.56 
```

But sometimes it is other files it is complaining about:
```
#0 34.56     torch>=1.6.0 from https://files.pythonhosted.org/packages/c8/21/25020cfdd9f564a72f400ee491610e50cb212e8add8031abaa959af6451e/torch-2.0.1-cp311-cp311-manylinux1_x86_64.whl (from sentence_transformers>=2.0.0->-r /code/requirements.txt (line 24)):
#0 34.56         Expected sha256 e617b1d0abaf6ced02dbb9486803abfef0d581609b09641b34fa315c9c40766d
#0 34.56              Got        eb1549116fc820ab99cfa93c389267ef7642dacdb7c5f790585cb264de1aab80
```

So unfortunately I am not able to full reproduce the error, since running the same docker build command returns different errors - however, always the "hashes does not match".

I am building from the main branch - I have tried others (older) as well.

I am running on a Intel Mac - MacOS 13.0
Docker version 24.0.2, build cb74dfc
(I use the same Docker environment for my daily job - running multiple containers all of the time)
I am new to Python, but have been developing software for 30+ years.
I use the hosted supabase - only version reference I can see says "Postgres 15.1.0.99".

BTW: Your installer assumes the people have psql installed - not everyone has - e.g. me, but I just ran the script directly.

**Comment by hash00x1** [comment]
Hi,
I fixed that by installing the packages from the environment file separately, via `pip install -r /backend/requirements.txt` and then just out-commenting the entries from the env-file, where the hash-issue seems to exist, via '#'. 
E.g., if the issue is with the torch package, the error lof tells you its a depencency from the package "sentence_transformers". So just open the environment.txt with an editor and put a hash in front of the package mentioned, as in #sentence_transformers.

I'm sure there is a more elegant way, but this solves the problem.
Good luck!

**Comment by andersir** [comment]
Thanks for the feedback. But doing it like that will that make it part of the Docker image?

**Comment by mgunnin** [comment]
Having the same issue. I did what @hash00x1 suggested and commented out "sentence_transformers>=2.0.0" in the backend requirements, and also increased the timeout just to be safe. The docker was finally installed, but now that I'm up and running, I have a feeling that certain features aren't working because of it.

So that's to say -- You can get around this error as mentioned. But there needs to be a fix that doesn't mess with the requirements.

**Comment by levistringer** [comment]
I noticed that no where in the python code is actually requiring the package `sentence_transformers`. I commented it out as well and haven't noticed any issues, but yes you're right by commenting it out, it will not be installed in the python backend container. 

> Thanks for the feedback. But doing it like that will that make it part of the Docker image?
