### ISSUE TITLE
[Issue] Referring to uploaded documents

### ISSUE THREAD

**Issue by basemaly** [StanGirard/quivr#855]
After uploading several documents I tried getting Quivr to summarize some of them, but it doesn't seem to be aware of any uploaded documents. Every time I ask, it responds with "I'm sorry, but I cannot summarize all the documents as I do not have access to them."

How do I get it to recognize and work with specific uploaded documents?

**Comment by beeduino** [comment]
Does it work in the case of one uploaded document?
It understands using "current context" to refer to one uploaded document.
I am on my day first of experimenting with quivr.

**Comment by basemaly** [comment]
I think it works alright with 1 document, but that defeats the purpose of uploading multiple documents. Does Quivr recognize individual documents or text by name?

**Comment by beeduino** [comment]
With three uploaded articles I was not able to get correct answers. When you're asking which three documents you have in context - it can take any titles from a reference list and compile the answer

**Comment by jignnsd** [comment]
I'm not sure that this be possible, the idea of this program is to answer questions given the documents uploaded. Not to give a summary of them. This is because all documents are embedded and these vectors are used to answer your question. My guess is that there is no way to do what you are trying to do with this project, is not intended to do so. 
I recommend you to upload the documents directly to chatgpt or Claude and ask for the summary of each. 
Regards
