### ISSUE TITLE
[Issue] Error sending mails for signing up

### ISSUE THREAD

**Issue by neumartin** [StanGirard/quivr#859]
Hi!

- Operating System: Fedora Workstation 38
- Docker and Docker Compose versions: 24.0.5 and v2.20.2
- Supabase version and setup: latest, local, and working with the structure of the tables created.
- Detailed steps to reproduce the issue: 

I cloned the repo, created a Resesnd account, API key, and successfully validated the domain, then I followed the steps, but when I tried to create the first user, I got "Error signing up: Error sending confirmation mail."

I tried a lot of different settings but couldn't make it work.
How can I fix that or create one user manually with a SQL script?

Thanks!

**Comment by ArnaudFelin** [comment]
hello, i had the same problem, i created a forwarding account and provided the api key but no it didn't work!

I think that the functionality with forwarding is not yet activated?

On the other hand, I've managed to set up email forwarding correctly on the supabase side (quirv uses supabase user management a priori).

To do this I used my google gmail account, but to get past security you need to activate double authentication and create an application password... it's this password that you need to use for the emails to be sent.

My problem is as follows: when I log on to quirv for the first time and want to create my first user, it confirms that an email has been sent and that I need to acknowledge receipt.

In my email there's a confirmation link and a code that I don't want to use:
1/ I can't see where I can use the code

2/ when I click on the link it takes me to a page it doesn't know!

From then on, I'm stuck.

I also tried to create a user directly in supabase, so I can connect to Quirv but something doesn't seem to work because I didn't follow the normal flow and the user isn't known on the database side given Quirv!!!!

If you ever have any information on the subject, I'm a taker.

**Comment by leonhardrocha** [comment]
I'm having the same problem as @neumartin . I had users signup at supabase before, but having problems with the user_id. After cleaning up the tables and running the script to create tables and run migrations, I cannot sign up with a new user because I never receive the confirmation e-mail.
