### ISSUE TITLE
Run Quivr without Supabase

### ISSUE THREAD

**Issue by priyadarshan85** [StanGirard/quivr#934]
Can we run Quivr without Supabase?

What Supabase services are being used? Is it just the database?

**Comment by GabriielEger** [comment]
Hi @priyadarshan85! I think that, right now, using supabase is making things more confortable for a open-source project... Maybe in future, when the system is really "ready" to be used, I guess (and hope) it will be possible and not a problem anymore. :)

**Comment by mort666** [comment]
Sorry but that really doesn't answer the OPs question. 

Personally I'd really like to use Quivr for a couple of tasks I'm working on as looks on the face of it potentially the right tool for the job, however categorically cannot use Supabase. In my case knowing what functionality is required from Supabase would go a long way to making a decision to use or not use, and as result as it stands it would probably require work provide a 'slot in' alternative backend. 

Which for example in may case would be something that I'd want 'tomorrow' as it where so I could progress my use case, and thus be it would be something that I'd arrange to sort the appropriate dev, and as a result ultimately feeding it back into the project, because a Dead Open Source project if I'm building something that leverages it become tech debt very quickly. 

However, having myself limited time, having some documentation/information detailing what elements of Supabase Quivr depends on means I can quickly assess if it is viable in the first instance for me to use, ensuring that there is no show stoppers to developing a alternative backend because some feature of Supabase is used and it is that one thing that locks you in to their platform can't be easily replicated else where.

And no offence, making something comfortable for building software, kind is a cop out, and doesn't in the long term and I've been around for the long term, I've seen this too many times, it makes objectively mediocre software, because you're not innovating, because of the over reliance on the third party. It is like a lot of the LLMs, after spending the last 5 months reverse engineering and dissecting these models, 'model safety' is making models useless over time, the more 'safety' applied to a model over time and during initial training, and it is pretty apparent from my testing of and GPT-3.5 and GPT-4, on release was able to identify safety warning markings that are internationally standardised for explosives reliably and consistently, and now it is unable to so in the current iteration, in so much one of the samples from the dataset today it thinks are colourful plastic tubes for a child to play with not the high explosive breaching charges that are actually in the box with the big orange warnings all over it.. Lazily building on top of these models reinforces bad decisions, normalises it and ultimately it means 'settling' for inferior models because a third party is controlling the reigns...
